// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type App struct {
	ID          string         `db:"id" json:"id"`
	Name        string         `db:"name" json:"name"`
	RepoUrl     string         `db:"repo_url" json:"repo_url"`
	Language    sql.NullString `db:"language" json:"language"`
	Port        sql.NullInt64  `db:"port" json:"port"`
	ContainerID sql.NullString `db:"container_id" json:"container_id"`
	ImageID     sql.NullString `db:"image_id" json:"image_id"`
	Status      sql.NullString `db:"status" json:"status"`
	ErrorMsg    sql.NullString `db:"error_msg" json:"error_msg"`
	CreatedAt   sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt   sql.NullTime   `db:"updated_at" json:"updated_at"`
}
