// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
)

type Querier interface {
	CreateApp(ctx context.Context, arg CreateAppParams) error
	DeleteApp(ctx context.Context, id string) error
	GetAllApps(ctx context.Context) ([]App, error)
	GetApp(ctx context.Context, id string) (App, error)
	GetAppByRepoUrl(ctx context.Context, repoUrl string) (App, error)
	UpdateApp(ctx context.Context, arg UpdateAppParams) error
}

var _ Querier = (*Queries)(nil)
